image: gitlab.jlab.pro:5050/jlab/gpu-dev

stages:
  - test
  - report

variables:
  JULIA_DEPOT_PATH: $CI_PROJECT_DIR/.julia

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .julia

.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags

.test_template: &test_base
  stage: test
  script:
    - julia --color=yes -e 'using InteractiveUtils; versioninfo()'
    - julia --color=yes --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test();'

.benchmark_template: &benchmark_base
  stage: test
  script:
    - git fetch
    - julia --color=yes --project=benchmark -e 'using Pkg; Pkg.develop(path=pwd()); Pkg.instantiate(); Pkg.build()'
    - julia --color=yes --project=benchmark .jlab/run_benchmarks.jl
  artifacts:
    paths:
      - benchmark*report.md

unit test:
  <<: *only-default
  <<: *test_base
  tags:
    - nvidia-docker
    - ubuntu

benchmark:
  <<: *only-default
  <<: *benchmark_base
  when: manual
  tags:
    - nvidia-docker
    - ubuntu

# requires environment variable REPO_TOKEN set up
# see https://gitlab.com/iterative.ai/cml-base-case
report:
  <<: *only-default
  stage: report
  needs: [benchmark]
  tags:
    - ubuntu
  script:
    - julia .jlab/process_reports.jl
